name: GitHub OIDC Sandbox

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  aws-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::766993824527:role/sirushi-github-oidc-iam-role
          aws-region: ap-northeast-1
      - name: Get AWS Account ID
        run: aws sts get-caller-identity
